### ISSUE TITLE
0.9.0 is currently broken

### ISSUE THREAD

**Issue by yurrriq** [lfex/lutil#47]
```
===> Failed to fetch and copy dep: {git,"https://github.com/lfex/lutil.git",
                                  {ref,
                                      "0ee02e01d643caba7a0b8365c477aea8d92bf309"}}
```

Related: https://github.com/lfex/ltest/issues/54

**Comment by yurrriq** [comment]
This happens on Travis as well as locally.

To reproduce:
```bash
$ git clone -n https://github.com/lfex/lutil.git /tmp/lutil
$ cd /tmp/lutil
$ git checkout -q 0ee02e01d643caba7a0b8365c477aea8d92bf309
fatal: reference is not a tree: 0ee02e01d643caba7a0b8365c477aea8d92bf309
```

**Comment by yurrriq** [comment]
Looks like this can be fixed on the ltest side.

**Comment by yurrriq** [comment]
A [quick search](https://github.com/search?q=lutil+0ee02e01d643caba7a0b8365c477aea8d92bf309&type=Code) shows [lfe-mug/lmug-elli](https://github.com/lfe-mug/lmug-elli/blob/080498ea4154bc5ffda8e23e7ee919722b17c5c5/rebar.lock#L38-L41) is affected too.

**Comment by yurrriq** [comment]
Locally, I found [lodox](https://github.com/lfe-rebar3/lodox/blob/631181eaf08e3e855e3e2ffa2d74ae382b3b4e11/rebar.lock#L29) and [exemplar](https://github.com/lfex/exemplar/pull/20) to be affected, in addition to [ltest](https://github.com/lfex/ltest/blob/0.9.0/rebar.lock#L19) and [lmug-elli](https://github.com/lfe-mug/lmug-elli/blob/0.3.3/rebar.lock#L40).

**Comment by oubiwann** [comment]
Yeah, everything is going to be affected:

 * the symptom arises due to the fact that rebar.lock files are kept in repo and save a particular commit id
 * the actual source of the problem is that all the commit ids in both ltest and lutil have changed, due to a rewrite (bad emails in the history for 100s of my commits)

As you noted, the workaround for this is to remove the rebar.lock file locally and let rebar3 regenerate it with the new commit ids for the various tags.

The good news:
 * all of the projects that I maintain will be updated and published to Hex.pm
 * due to issues with generating a Hex.pm release in a profile, rebar.lock files will not be saved with my projects anymore, so this particular issue  won't occur, should commit ids ever change again

So, have patience -- once these projects are out of the RC stage, they should be in pretty good shape and all these issues will have been worked around.
